#!/usr/bin/php

<?php
$SERVER = $_SERVER['argv'][1];
$RECORD = $_SERVER['argv'][2]; 
$EXPECTED = $_SERVER['argv'][3];

// Try to get the IP - Kill if takes longer than 3 seconds
$output = exec("dig +short $RECORD @$SERVER & sleep 2; kill $!");

print "Output was: $output\n";
print "Expected was: $EXPECTED\n";

if ($output == $EXPECTED)
{ print "SUCCESS"; }
else
{ print "FAILURE"; }
?>
