#!/usr/bin/php

<?php
$URL = 'http://' . $_SERVER['argv'][1] . $_SERVER['argv'][2];
$HASH = $_SERVER['argv'][3];

// Get the contents of the URL and the MD5
$output = DownloadUrl($URL);
$md5 = md5($output);

//print "Output was: $output\n";
//print "MD5 is: $md5\n";
//print "Expected MD5: $HASH\n";

// If the hashes match, update the success counter
if ($md5 == $HASH)
{ print "SUCCESS"; }
else
{ print "FAILURE";
  print $md5; }

function DownloadUrl($Url){
    
    // is curl installed?
    if (!function_exists('curl_init')){ 
        die('CURL is not installed!');
    }
    
    // create a new curl resource
    $ch = curl_init();

    // set URL to download
    curl_setopt($ch, CURLOPT_URL, $Url);

    // set referer:
    //curl_setopt($ch, CURLOPT_REFERER, "http://www.google.com/");

    // user agent:
    //curl_setopt($ch, CURLOPT_USERAGENT, "MozillaXYZ/1.0");

    // remove header? 0 = yes, 1 = no
    curl_setopt($ch, CURLOPT_HEADER, 0);

    // should curl return or print the data? true = return, false = print
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);

    // timeout in seconds
    curl_setopt($ch, CURLOPT_TIMEOUT, 2);

    // download the given URL, and return output
    $output = curl_exec($ch);

    // close the curl resource, and free system resources
    curl_close($ch);

    // print output
    return $output;
}

?>
