#!/usr/bin/php

<?php
$SERVER = $_SERVER['argv'][1];
$USER = $_SERVER['argv'][2];
$PASSWORD = $_SERVER['argv'][3];

// Try to get the IP - Kill if takes longer than 3 seconds
$output = exec("python ../resources/ssh.py $SERVER -u $USER -P 22 -p $PASSWORD & sleep 2; k$

print "Output was: $output\n";
print "Expected was: $EXPECTED\n";

if ($output == $EXPECTED)
{ print "SUCCESS"; }
else
{ print "FAILURE"; }
?>
