#!/usr/bin/php

<?php
$SERVER = $_SERVER['argv'][1];
$USER = $_SERVER['argv'][2]; 
$PASSWORD = $_SERVER['argv'][3];
$EXPECTED = "SUCCESS";
// Try to get the IP - Kill if takes longer than 3 seconds
$output = exec("python /var/www/html/se/resources/ssh.py $SERVER -u $USER -P 22 -p $PASSWORD & sleep 2; kill $!");

print "Output was: $output\n";
print "Expected was: $EXPECTED\n";

if ($output == $EXPECTED)
{ print "SUCCESS"; }
else
{ print "FAILURE"; }
?>
